# frozen_string_literal: true

source "https://rubygems.org"

gem "parser"

group :development do
  gem "solargraph"
  gem "yard"
  gem "rubocop", require: false
  gem "pry"
  gem "pry-byebug"
  gem "rspec"
end
