# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activesupport"

group :development do
  gem "solargraph"
  gem "rufo"
  gem "pry"
end
